processing:
  no_stew: True

plot:
  dir: output/


time_spans:

  - title: 'Synoptic'
    dir: 'output/SYN_Lyg_CIII_new_syn/'
    start_date: '2021-12-01'
    end_date: '2022-08-30'
    study_id: '1963'
    spec_win: 'Ly-gamma-CIII group bin (1/4)'
    plot_marker: 's'

  - title: 'Synoptic'
    dir: 'output/SYN_Lyg_CIII_new_syn/'
    start_date: '2022-08-30'
    end_date: '2022-11-25'
    study_id: '1963'
    spec_win: 'Ly-gamma-CIII group bin (Merged)'
    plot_marker: 's'

  - title: 'RSW'
    dir: 'output/SYN_Lyg_CIII_new_rsw/'
    start_date: '2021-12-01'
    end_date: '2022-08-30'
    study_id: '1975'
    spec_win: 'Ly-g-CIII group bin (1/3)'
    plot_marker: 'D'

  - title: 'RSW'
    dir: 'output/SYN_Lyg_CIII_new_rsw/'
    start_date: '2022-08-30'
    end_date: '2022-11-25'
    study_id: '1975'
    spec_win: 'Ly-g-CIII group bin (Merged)'
    plot_marker: 'D'
