processing:
  jitter_correction: ['fits', 'kernels']

plot:
  dir: output/


time_spans:

  - title: 'Synoptic'
    dir: 'output/SYN_Lyg_CIII_new_syn/'
    start_date: '2021-12-01'
    end_date: '2023-12-31'
    study_id: 1963
    spec_win: 'Ly-gamma-CIII group (Merged)'
    plot_marker: 's'

  - title: 'RSW'
    dir: 'output/SYN_Lyg_CIII_new_rsw/'
    start_date: '2021-12-01'
    end_date: '2023-12-31'
    study_id: 1975
    spec_win: 'Ly-g-CIII group (Merged)'
    plot_marker: 'D'
