processing:
  jitter_correction: ['dummy']

plot:
  dir: output/test/plot/


time_spans:

  - title: 'Synoptic'
    dir: 'output/test/SYN_Lyg_CIII_new_syn/'
    start_date: '2022-01-07'
    end_date: '2022-01-15'
    study_id: 1963
    spec_win: 'Ly-gamma-CIII group (Merged)'
    plot_marker: 's'
